### ISSUE TITLE
ArrayField not working as expect with initialValues

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [joepuzzo/informed#157]
I am using `ArrayField` in update form and I use `initialValues` props for add default value, but the value not appear in the fields inside `ArrayField`

```
initialValues={{
    name: "John",
    email: "john@email.com",
    departments: ["financial", "accounting"]
}}
```
I use normal Text component for **name** and **email** fields and it working fine but **departments** is not working which is inside `ArrayField`, it's hard to explain by text I put the example link when you try it you will understand what i mean.

[codesandbox](https://codesandbox.io/s/l4rvzk8kwl)

**Comment by joepuzzo** [comment]
Hmm i dont think array fields support initial values yet let me look into it. ( it should if it doesent so i will add to my backlog )

**Comment by kyawkyawsoezhu** [comment]
thanks @joepuzzo ,  it's ok to just use array map to render multiple fields, but I also need dynamic array, I tried to do manually by using addValue and removeValue from formApi, but more error occur.
anyway to do dynamic array right now before   `ArrayField` support initial values

**Comment by joepuzzo** [comment]
Hey @kyawkyawsoezhu This is now fixed and working in latest release `2.1.7` Let me know how that goes. Note i still need to add docs for this but what your doing should now work.. also note that when you remove and then add back it will fill the initial value back in.. not sure if thats expected behaviour or not but i will think about it.

**Comment by kyawkyawsoezhu** [comment]
@joepuzzo thanks for quick update, but remove should gone forever, and remove not working properly, it always remove the first one even if you click the second or last remove button.

P.S I've updated dependency in the  same **codesandbox**

**Comment by luisccf** [comment]
@kyawkyawsoezhu I was having a similar problem. I fixed it by adding the key to the parent component like it is in the docs (on the label tag just after the fields map).

https://joepuzzo.github.io/informed/?selectedKind=Arrays&selectedStory=Dynamic%20Arrays&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by luisccf** [comment]
I still don't get it how I can populate ArrayField. I tried with setValues but it didn't work. I also tried with initialValues, but something weird is happening. The values are there, but I have to click on the add button to make they appear.

Say I have a `{ siblings: [1, 2, 3] }` as initialValues. The form is empty at first, but when I click on the add button, the first input appears with the value 1. If I click again, then a second input appears with the value 2 and so on.

Is there a way to already render the inputs that have initial values without having to click on the add button? (which I think is the expected behavior)

**Comment by joepuzzo** [comment]
Umm can i see your code @luisccf ? Also make sure you're using the latest release.

**Comment by kyawkyawsoezhu** [comment]
@luisccf  the initialValues not working was fixed in 2.1.7

**Comment by luisccf** [comment]
Updated to 2.1.7 (thought I had updated it already) and now it works using initialValues. Thanks!
